"use client";

import {
  Brain,
  Zap,
  Rocket,
  Scale,
  Calculator,
  Atom,
  FlaskConical,
  Dna,
  Code2,
  BookOpen,
  Globe,
  ScrollText,
  Library,
  GraduationCap,
  Wrench,
  ExternalLink,
  Paperclip,
  Upload,
  Palette,
  HelpCircle,
  Trophy,
  BookText,
  Calendar,
  FileText,
  Search,
  MessageSquare,
  Settings,
  ChevronDown,
  ChevronRight,
  Plus,
  X,
  Send,
  Menu,
  PanelLeftClose,
  LogOut,
  Star,
  Sparkles,
  Bot,
  User,
  Trash2,
  Check,
  Clock,
  type LucideProps,
} from "lucide-react";
import type { FC } from "react";

const iconMap: Record<string, FC<LucideProps>> = {
  brain: Brain,
  zap: Zap,
  rocket: Rocket,
  scale: Scale,
  calculator: Calculator,
  atom: Atom,
  "flask-conical": FlaskConical,
  dna: Dna,
  "code-2": Code2,
  "book-open": BookOpen,
  globe: Globe,
  "scroll-text": ScrollText,
  library: Library,
  "graduation-cap": GraduationCap,
  wrench: Wrench,
  "external-link": ExternalLink,
  paperclip: Paperclip,
  upload: Upload,
  palette: Palette,
  "help-circle": HelpCircle,
  trophy: Trophy,
  "book-text": BookText,
  calendar: Calendar,
  "file-text": FileText,
  search: Search,
  "message-square": MessageSquare,
  settings: Settings,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  plus: Plus,
  x: X,
  send: Send,
  menu: Menu,
  "panel-left-close": PanelLeftClose,
  "log-out": LogOut,
  star: Star,
  sparkles: Sparkles,
  bot: Bot,
  user: User,
  trash2: Trash2,
  check: Check,
  clock: Clock,
};

interface IconProps extends LucideProps {
  name: string;
}

export function Icon({ name, ...props }: IconProps) {
  const IconComponent = iconMap[name];
  if (!IconComponent) return null;
  return <IconComponent {...props} />;
}

// Re-export commonly used icons directly for convenience
export {
  Brain,
  Zap,
  Rocket,
  Scale,
  Calculator,
  Atom,
  FlaskConical,
  Dna,
  Code2,
  BookOpen,
  Globe,
  ScrollText,
  Library,
  GraduationCap,
  Wrench,
  ExternalLink,
  Paperclip,
  Upload,
  Palette,
  HelpCircle,
  Trophy,
  BookText,
  Calendar,
  FileText,
  Search,
  MessageSquare,
  Settings,
  ChevronDown,
  ChevronRight,
  Plus,
  X,
  Send,
  Menu,
  PanelLeftClose,
  LogOut,
  Star,
  Sparkles,
  Bot,
  User,
  Trash2,
  Check,
  Clock,
};
